[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "" # Uses the default ENTRYPOINT from the openrouteservice Docker image
restartPolicyType = "on_failure"

[env]
XMS = "200m"
XMX = "400m"
PORT = "8082"
CONTAINER_LOG_LEVEL = "INFO"
